sudo: required
language: generic
services:
  - docker

script:
  - docker build -t thanneeruravi22/multi-client ./client
  - docker build -t thanneeruravi22/multi-nginx ./nginx
  - docker build -t thanneeruravi22/multi-server ./server
  - docker build -t thanneeruravi22/multi-worker ./worker
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push image to docker hub
  - docker push thanneeruravi22/multi-client
  - docker push thanneeruravi22/multi-nginx
  - docker push thanneeruravi22/multi-server
  - docker push thanneeruravi22/multi-worker
