sudo: required
language: generic
services:
  - docker

script:
  - docker build -t thanneeruravi/multi-client ./client
  - docker build -t thanneeruravi/multi-nginx ./nginx
  - docker build -t thanneeruravi/multi-server ./server
  - docker build -t thanneeruravi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker push thanneeruravi/multi-client
  - docker push thanneeruravi/multi-nginx
  - docker push thanneeruravi/multi-server
  - docker push thanneeruravi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-159571103942
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
