sudo: required
services:
  - docker

before_install:
  - docker build -t thanneeruravi22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thanneeruravi22/react-test npm test

after_success:
  - docker build -t thanneeruravi22/multi-client ./client
  - docker build -t thanneeruravi22/multi-nginx ./nginx
  - docker build -t thanneeruravi22/multi-server ./server
  - docker build -t thanneeruravi22/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker push thanneeruravi22/multi-client
  - docker push thanneeruravi22/multi-nginx
  - docker push thanneeruravi22/multi-server
  - docker push thanneeruravi22/multi-worker
